services:
  sp-sap-webpriv-build:
    container_name: sap-webpriv-run
    image: sap-webpriv-img
    build:
      dockerfile: sp-sap-webpriv-build-split-docker
      target: sap-webpriv-img
      args:
        #BASE BUILD
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - SP_SHARED_ENV_GROUP=${SP_SHARED_ENV_GROUP}
        - SP_SHARED_GROUP_NAME=${SP_SHARED_GROUP_NAME}
        - SP_SHARED_DIR=${SP_SHARED_DIR}
        - SP_AGEDIR=${SP_AGEDIR}
        - SP_AGEDIR_KEYS=${SP_AGEDIR_KEYS}
        - SP_AGEDIR_INFO=${SP_AGEDIR_INFO}
        - SP_APP_STEP_VERSION=${SP_APP_STEP_VERSION}
        - SP_APP_WEBPRIV_VERSION=${SP_APP_WEBPRIV_VERSION}
        #Container Specific
        - CSR_LOCATE=${CSR_LOCATE}
        - SIGNED_CERT=${SIGNED_CERT}
        - SP_SAP_DIR=/srv
        - SP_SAP_APP_DIR=/srv/webpriv
        - SP_STEP_HOST=${SP_STEP_HOST}
        - SP_STEPPATH=/srv/webpriv/.step
        - SP_WEBPRIV_CERT_DUR=48h
        - SP_CONTAINER_NAME=sap-webpriv-run
        - SP_WEBPRIV_EXP_CHECK=85%
        - SP_TARGET_HOST=${SP_TARGET_HOST}
        - SP_TARGET_PORT=${SP_TARGET_PORT}
        - SP_ZSRCSRV=${WEBPRIV_HOST_PORT}
        - ZABAP_SRCSRV=${WEBPRIV_ZABAP_SRCSRV}
        - SP_ABAP_SETUP=YES
        - SP_ABAP_HTTPS_PORT=${SP_ABAP_HTTPS_PORT} 
        - SP_ABAP_HOST_FQDN=${SP_ABAP_HOST_FQDN} 
        - SP_ABAP_MSHOST_FQDN=${SP_ABAP_MSHOST_FQDN} 
        - SP_ABAP_HTTP_PORT=${SP_ABAP_HTTP_PORT} 
        - SP_ABAP_MS_PORT=${SP_ABAP_MS_PORT} 
        - SP_ABAP_SID=${SP_ABAP_SID} 
        - ZWEBADM_HOST=${WEBPRIV_HOST}.${DOMAIN}
        - ZWEBADM_PORT=${WEBPRIV_ZWEBADM_PORT}
        - SP_RCOUNT=${SP_RCOUNT} 
        - SP_RDAY=${SP_RDAY} 
        - SP_RENEW_VALID=${SP_RENEW_VALID} 
        - SP_ROOTC=${SP_ROOTC} 
        - SP_ROOTCA_VALID=${SP_ROOTCA_VALID} 
        - SP_EMAIL=${SP_EMAIL}
        - SP_ROOTCN=${SP_ROOTCN} 
        - SP_RTIME=${SP_RTIME} 
        - SP_RSLEEP=${SP_RSLEEP}
    hostname: ${WEBPRIV_HOST}
    domainname: ${DOMAIN}
    ports:
      - "${WEBPRIV_HOST_PORT}:${WEBPRIV_HOST_PORT}"
      - "${WEBPRIV_ZWEBADM_PORT}:${WEBPRIV_ZWEBADM_PORT}"
      - "${WEBPRIV_ZABAP_SRCSRV}:${WEBPRIV_ZABAP_SRCSRV}"
    networks:
      - sp-sap-net1
    depends_on:
      sp-sap-step-build:
        condition: service_started
    volumes:
      - sp_sap_keys_vol1:/srv/shared/.age/.keys:ro
      - sp_sap_info_vol1:/srv/shared/.age/.info:ro
      - sp_sap_webpriv_vol1:/srv
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#      - shared:/mnt/shared
    tty: true
volumes:
  sp_sap_keys_vol1:
    external: true
  sp_sap_info_vol1:
    external: true
  sp_sap_webpriv_vol1:
    external: true
  shared:
networks:
  sp-sap-net1:
    external: true
